# Define the stages of the CI/CD pipeline
stages:
  - test    # Test stage
  - build   # Build stage
  - deploy  # Deployment stage

# Job to run unit tests
test-job1:
  stage: test   # Run in the "test" stage
  script:
    - gradle test  # Run the Gradle test command

# Job to build the project
build-job:
  stage: build  # Run in the "build" stage
  script:
    - gradle build  # Run the Gradle build command
  artifacts:
    paths:
      - build/libs/*.jar  # Publish JAR files as artifacts for later stages

# Job to deploy to production
deploy-prod:
  stage: deploy    # Run in the "deploy" stage
  script:
    - gradle deploy  # Run the Gradle deploy command
  environment:
    name: production  # Define the environment as "production"